// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantorID");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("AlbumId");

                    b.HasIndex("CantorID");

                    b.ToTable("Albuns");
                });

            modelBuilder.Entity("WebApplication1.Models.Cantor", b =>
                {
                    b.Property<int>("CantorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<byte[]>("imgCantor");

                    b.HasKey("CantorID");

                    b.ToTable("Cantores");
                });

            modelBuilder.Entity("WebApplication1.Models.Musica", b =>
                {
                    b.Property<int>("MusicaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlbumId");

                    b.Property<int>("CantorID");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<byte[]>("imgMusica");

                    b.HasKey("MusicaID");

                    b.HasIndex("AlbumId");

                    b.HasIndex("CantorID");

                    b.ToTable("Musicas");
                });

            modelBuilder.Entity("WebApplication1.Models.Album", b =>
                {
                    b.HasOne("WebApplication1.Models.Cantor", "cantor")
                        .WithMany("Albums")
                        .HasForeignKey("CantorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication1.Models.Musica", b =>
                {
                    b.HasOne("WebApplication1.Models.Album", "album")
                        .WithMany("Musicas")
                        .HasForeignKey("AlbumId");

                    b.HasOne("WebApplication1.Models.Cantor")
                        .WithMany("Musicas")
                        .HasForeignKey("CantorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
